### ISSUE TITLE
Default Omni Range is larger than entire Solar System

### ISSUE THREAD

**Issue by kasanryukin** [Y3mo/SETI-RemoteTech#1]
The 900 Gm Omni Antenna covers the entire solar system, not just Kerbin's SOI as advertised.  Fix: Change the value in the config file (line 40) from Omni = 9E+11 to Omni = 9E+7.  This gives it a value of 90 Million Meters, 6 million more than Kerbins SOI.

Edit: Reading is hard, and the 900 Gm is intentional.  Disregard. (But recommended change to preserve the balance of the source mod)

**Comment by Y3mo** [comment]
Hey, thanks for the feedback, that reminds me that I wanted to adjust the colors of the stations!

The SETI config is intended to be something between the normal remote tech and squads proposed 1.1 (now delayed) com system (which only requires com sat networks for non-kerbin planets).
